[project]
name = "billingsystem"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KrzysDev", email = "krzysiekk.sokolowski@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "pillow>=12.3.0",
    "ptyprocess>=0.7.0",
    "pyscreenshot>=3.1",
    "pywinpty>=3.0.5",
    "uvicorn>=0.52.4",
]

[project.scripts]
billingsystem = "billingsystem:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
