[project]
name = "presentationgenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "KrzysDev", email = "krzysiekk.sokolowski@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi>=0.141.1",
    "ollama>=0.6.2",
    "pydantic[email]>=2.13.5",
    "pypdf>=6.19.0",
    "python-multipart>=0.0.32",
    "slowapi>=0.1.10",
    "supabase>=2.31.0",
    "textract>=2.1.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
presentationgenerator = "presentationgenerator:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
