"""
Router for saved presentations — list, save, and retrieve by ID.
All endpoints require a valid JWT access token.
"""

from fastapi import APIRouter, Request, Depends
from presentationgenerator.models.schemas import (
    SavePresentationRequest,
    SavedPresentation,
    SavedPresentationFull,
)
from presentationgenerator.services.auth_serivce import AuthService
from presentationgenerator.services.presentation_storage_service import PresentationStorageService

router = APIRouter(prefix="/presentations", tags=["presentations"])

auth = AuthService()
storage = PresentationStorageService()


# ------------------------------------------------------------------
# GET /presentations/me  — list all presentations for the current user
# ------------------------------------------------------------------
@router.get("/me", response_model=list[SavedPresentation], summary="List all saved presentations for the authenticated user")
async def list_my_presentations(token: str):
    """
    Returns all presentations saved by the authenticated user,
    ordered from newest to oldest. Does not include HTML to keep
    the response lightweight — use GET /presentations/{id} for the full HTML.
    """
    user = auth.verify_token(token)
    return storage.get_all_for_user(str(user.id))


# ------------------------------------------------------------------
# GET /presentations/{id}  — retrieve a single presentation with full HTML
# ------------------------------------------------------------------
@router.get("/{presentation_id}", response_model=SavedPresentationFull, summary="Get a single saved presentation by ID (includes full HTML)")
async def get_presentation(presentation_id: str, token: str):
    """
    Returns the full data of a saved presentation, including the HTML field.
    Returns 404 if the presentation does not exist or belongs to a different user.
    """
    user = auth.verify_token(token)
    return storage.get_by_id(presentation_id=presentation_id, user_id=str(user.id))


# ------------------------------------------------------------------
# POST /presentations/save  — explicitly save a presentation
# ------------------------------------------------------------------
@router.post("/save", response_model=SavedPresentation, status_code=201, summary="Save a generated presentation to the database")
async def save_presentation(body: SavePresentationRequest):
    """
    Saves a presentation that was previously generated by POST /presentation.
    The client passes the token, topic, html, and slides_count from the generation response.
    Returns the saved row (without HTML) on success.
    """
    user = auth.verify_token(body.token)
    saved = storage.save(
        user_id=str(user.id),
        topic=body.topic,
        html=body.html,
        slides_count=body.slides_count,
    )
    return saved
